export const EXTERNAL_CONFIG_PATH = './config/config.yaml';

export const VALID_SIZES = ['small', 'full'] as const;

export const TIME_REGEX = /^(\d+)(s|m|h|d|w|mo|y)$/;
export const REDDIT_SORT_REGEX = /^(top|hot|new|controversial)$/;
export const REDDIT_TIME_REGEX = /^(hour|day|week|month|year|all)$/;
export const TARGET_REGEX = /^(_blank|_self|_parent|_top)$/;
export const CSS_UNIT_REGEX =
  /^\d+(\.\d+)?(px|rem|em|ex|ch|lh|pt|pc|cm|mm|in|Q|%|vw|vh|vmin|vmax|svw|svh|lvw|lvh|dvw|dvh|cqw|cqh|cqi|cqb|cqmin|cqmax)$/;
export const CSS_PERCENT_REGEX = /^(\d+(\.\d+)?)%$/;

export const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  JPY: '¥',
  CNY: '¥',
  KRW: '₩',
  INR: '₹',
  IDR: 'Rp',
  THB: '฿',
  VND: '₫',
  AUD: 'A$',
  CAD: 'C$',
  CHF: 'CHF',
  HKD: 'HK$',
  SGD: 'S$',
  BRL: 'R$',
  MXN: 'MX$',
  PHP: '₱',
  MYR: 'RM',
  TRY: '₺',
  RUB: '₽',
  ZAR: 'R',
  NZD: 'NZ$',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  PLN: 'zł',
  BDT: '৳',
  PKR: '₨',
  EGP: 'E£',
  NGN: '₦',
  GHS: '₵',
  KES: 'KSh',
  UAH: '₴',
  CZK: 'Kč',
  HUF: 'Ft',
  ILS: '₪',
  CLP: 'CLP$',
  COP: 'COP$',
  PEN: 'S/',
  ARS: 'AR$',
  BGN: 'лв',
  RON: 'lei',
  TWD: 'NT$',
  AED: 'د.إ',
  SAR: 'ر.س',
  ISK: 'kr',
  BHD: '.د.ب',
  KWD: 'د.ك',
  QAR: 'ر.ق',
  DZD: 'د.ج',
  MAD: 'د.م.',
  TND: 'د.ت',
  LKR: 'Rs',
  NPR: 'Rs',
  MMK: 'K',
  KHR: '៛',
  LAK: '₭',
  BND: 'B$',
  PYG: '₲',
  UYU: '$U',
  KZT: '₸',
  UZS: "so'm",
  GEL: '₾',
  AMD: '֏',
  AZN: '₼',
  BYN: 'Br',
  RSD: 'дин.',
  MKD: 'ден',
  ALL: 'L',
  BAM: 'KM',
  HRK: 'kn',
  CUP: '₱',
  DOP: 'RD$',
  GTQ: 'Q',
  HNL: 'L',
  NIO: 'C$',
  CRC: '₡',
  PAB: 'B/.',
  XAF: 'Fr',
  XOF: 'CFA',
  XCD: 'EC$',
  BSD: 'B$',
  BBD: 'Bds$',
  JMD: 'J$',
  TTD: 'TT$',
  KYD: 'CI$',
  HTG: 'G',
  MDL: 'L',
  CVE: 'Esc',
  MZN: 'MT',
  AOA: 'Kz',
  ZMW: 'ZK',
  MWK: 'MK',
  BWP: 'P',
  SCR: 'SR',
  MUR: '₨',
  MVR: 'Rf',
  BTN: 'Nu.',
  AFN: '؋',
  IRR: '﷼',
  IQD: 'ع.د',
  JOD: 'د.ا',
  LBP: 'ل.ل',
  SYP: '£S',
};
